<a href="https://colab.research.google.com/github/Chirag314/pytorch/blob/main/pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.1.0+cu121'

In [2]:
import numpy as np
lst=[3,4,5,6]
arr=np.array(lst)
arr.dtype

dtype('int64')

In [3]:
tensors=torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

In [4]:
tensor_arr=torch.tensor(arr)

In [6]:
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [7]:
torch.ones(2,3,dtype=torch.int16)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

In [10]:
a=torch.tensor([3,4,5],dtype=torch.int32)
b=torch.tensor([4,5,6],dtype=torch.int32)
print(a+b)

tensor([ 7,  9, 11], dtype=torch.int32)
